services:
  iowarp:
    image: iowarp/iowarp-deps:latest
    container_name: iowarp  
    shm_size: 8g
    mem_limit: 8g
    volumes:
      - ${IOWARP}/cte-hermes-shm:/cte-hermes-shm
      - ${IOWARP}/iowarp-runtime:/iowarp-runtime
      - ${IOWARP}/content-transfer-engine:/content-transfer-engine
    stdin_open: true
    tty: true
    network_mode: host