name: iowarp

base: core24

icon: 'snap/iowarp.png'

license: BSD-3-Clause

version: '0.0.2'

summary: Advanced Data Management for Scientific Workflows

description: |
  IOWarp is a comprehensive data management platform
  designed to address the unique challenges in scientific workflows
  that integrate simulation, analytics, and Artificial Intelligence (AI).
  IOWarp builds on existing storage infrastructures,
  optimizing data flow and providing a scalable,
  adaptable platform for managing diverse data needs in modern scientific workflows,
  particularly those augmented by AI.

grade: stable

confinement: strict

apps:
  iowarp:
    command: bin/hg_info
    plugs: [home, network]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:usr/lib/x86_64-linux-gnu:usr/lib/libpsm1:$SNAP/usr/lib

parts:
  iowarp:
    stage-packages:
      - libboost-dev
      - libboost-fiber-dev
      - libboost-regex-dev
      - libpsm-infinipath1-dev      
      - openmpi-bin
      - openmpi-common
      - mpi-default-dev
    plugin: dump
    source: ./vcpkg/installed/x64-linux/
  
  