name: iowarp
base: core24
version: '0.0.0'
summary: Advanced Data Management for Scientific Workflows
description: |
  IOWarp is a comprehensive data management platform
  designed to address the unique challenges in scientific workflows
  that integrate simulation, analytics, and Artificial Intelligence (AI).
  IOWarp builds on existing storage infrastructures,
  optimizing data flow and providing a scalable,
  adaptable platform for managing diverse data needs in modern scientific workflows,
  particularly those augmented by AI.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  hermes:
    # See 'snapcraft plugins'
    plugin: dump
    source: ./vcpkg/installed/x64-linux/
