name: Docker All

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  BASE_IMAGE: iowarp/iowarp-base
  DEPS_SPACK_IMAGE: iowarp/iowarp-deps-spack
  DEPS_IMAGE: iowarp/iowarp-deps
  USER_IMAGE: iowarp/iowarp-user

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push base image
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/iowarp-base.Dockerfile
          push: true
          tags: ${{ env.BASE_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.BASE_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.BASE_IMAGE }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Build and push deps-spack image
      - name: Build and push deps-spack image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/iowarp-deps-spack.Dockerfile
          push: true
          tags: ${{ env.DEPS_SPACK_IMAGE }}:latest
          cache-from: |
            type=registry,ref=${{ env.DEPS_SPACK_IMAGE }}:buildcache
            type=registry,ref=${{ env.BASE_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DEPS_SPACK_IMAGE }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Build and push deps image
      - name: Build and push deps image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/iowarp-deps.Dockerfile
          push: true
          tags: ${{ env.DEPS_IMAGE }}:latest
          cache-from: |
            type=registry,ref=${{ env.DEPS_IMAGE }}:buildcache
            type=registry,ref=${{ env.DEPS_SPACK_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DEPS_IMAGE }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Build and push user image
      - name: Build and push user image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/iowarp-user.Dockerfile
          push: true
          tags: ${{ env.USER_IMAGE }}:latest
          cache-from: |
            type=registry,ref=${{ env.USER_IMAGE }}:buildcache
            type=registry,ref=${{ env.DEPS_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.USER_IMAGE }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1