name: docker all
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push iowarp-base
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/iowarp-base.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          tags: iowarp/iowarp-base:latest
      - name: Build and push iowarp-deps-spack
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/iowarp-deps-spack.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          tags: iowarp/iowarp-deps-spack:latest
      - name: Build and push iowarp-deps
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/iowarp-deps.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          tags: iowarp/iowarp-deps:latest
      - name: Build and push iowarp-user
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/iowarp-user.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          tags: iowarp/iowarp-user:latest