name: lin

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run:  |
          sudo apt-get update
          sudo apt-get install \
          autoconf automake autoconf-archive doxygen \
          libboost-dev libboost-fiber-dev libboost-regex-dev \
          libelf-dev openmpi-bin openmpi-common mpi-default-dev python3-dev 
      - name: test
        shell: bash
        run: |
          ./install.sh
