name: mac

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run:  |
          brew install \
          autoconf automake autoconf-archive boost doxygen \
          libelf libomp open-mpi
      - name: test
        shell: bash
        run: |
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"	  
          ./install.sh
