name: mac

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run:  |
          brew install \
          autoconf automake autoconf-archive doxygen \
          boost \
          libelf libomp open-mpi
      - name: test
        shell: bash
        run: |
          ls /usr/local/Cellar/libomp/20.1.1
          export LDFLAGS="-L/usr/local/Cellar/libomp/20.1.1/lib"
          export CPPFLAGS="-I/usr/local/Cellar/libomp/20.1.1/include"
          ./install.sh
