name: mac

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run:  |
          brew install \
          autoconf automake autoconf-archive doxygen \
          boost \
          libelf open-mpi
      - name: test
        shell: bash
        run: |
          ./install.sh


